version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15-alpine
    container_name: tactical-operator-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: tactical_operator
      POSTGRES_USER: tactical_user
      POSTGRES_PASSWORD: CHANGE_THIS_PASSWORD_IN_PRODUCTION
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tactical_user -d tactical_operator"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:
    driver: local
